# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='describe',
            field=models.TextField(verbose_name='城市描述'),
        ),
    ]
