# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180905_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('education_institution', '教育机构'), ('personal', '个人'), ('company', '企业')], default='education_institution', max_length=30, verbose_name='机构类别'),
        ),
    ]
