# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180907_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m/%d', verbose_name='讲师头像'),
        ),
    ]
