# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-26 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
