# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180823_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brithday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
